<style type="text/css">

.footer-menu{
  margin: 0;
  width: 100%;
  position: absolute;
  bottom: 0;
  background-color: #9F9F9F;
}

</style>

<div class=".footer-menu">
    <!-- <ul class="nav nav-pills nav-justified"> -->
      <div class="col-xs-4">
      <!-- <li role="presentation"> --><a class="glyphicon glyphicon-home" href="#"></a><!-- </li> -->
      </div>
      <div class="col-xs-4">
      <!-- <li role="presentation"> --><a class="glyphicon glyphicon-send" href="#"></a><!-- </li> -->
      </div>
      <div class="col-xs-4">
      <!-- <li role="presentation"> --><a class="glyphicon glyphicon-user" href="#"></a><!-- </li> -->
      </div>
    <!-- </ul> -->
</div>
